import type { Doctor, Patient, Exercise, Plan } from '../types'

export const mockDoctor: Doctor = {
  id: '1',
  name: 'Dr. Smith',
  email: 'smith@clinic.com',
  phone: '+1 (555) 123-4567',
  address: '123 Medical Center Drive, Suite 100, Springfield, IL 62701',
  photo: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=400&h=400&fit=crop',
  specialization: 'Orthopedic',
  age: 45,
}

export const mockDoctors: (Doctor & { password: string })[] = [
  {
    ...mockDoctor,
    password: 'smith123',
  },
  {
    id: '2',
    name: 'Dr. Johnson',
    email: 'johnson@clinic.com',
    phone: '+1 (555) 234-5678',
    address: '456 Health Plaza, Suite 200, Springfield, IL 62704',
    photo: 'https://images.unsplash.com/photo-1516574187841-cb9cc2ca948b?w=400&h=400&fit=crop',
    specialization: 'Physical Therapy',
    age: 38,
    password: 'johnson123',
  },
  {
    id: '3',
    name: 'Dr. Williams',
    email: 'williams@clinic.com',
    phone: '+1 (555) 345-6789',
    address: '789 Wellness Center, Suite 300, Springfield, IL 62705',
    photo: 'https://images.unsplash.com/photo-1559839734033-6461accc113d?w=400&h=400&fit=crop',
    specialization: 'Sports Medicine',
    age: 42,
    password: 'williams123',
  },
]

export const mockPatients: Patient[] = [
  // Dr. Smith's patients
  {
    id: '1',
    doctorId: '1',
    doctor: mockDoctor,
    name: 'John Doe',
    email: 'john@example.com',
    phone: '+1 (555) 987-6543',
    address: '456 Oak Street, Springfield, IL 62702',
    photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop',
    snsId: 'SNS123456',
  },
  {
    id: '2',
    doctorId: '1',
    doctor: mockDoctor,
    name: 'Jane Smith',
    email: 'jane@example.com',
    phone: '+1 (555) 654-3210',
    address: '789 Elm Avenue, Springfield, IL 62703',
    photo: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&h=400&fit=crop',
    snsId: 'SNS789012',
  },
  {
    id: '5',
    doctorId: '1',
    doctor: mockDoctor,
    name: 'Robert Johnson',
    email: 'robert.j@example.com',
    phone: '+1 (555) 543-2109',
    address: '321 Cedar Lane, Springfield, IL 62708',
    photo: 'https://images.unsplash.com/photo-1500595046891-e46f4cdeaa82?w=400&h=400&fit=crop',
    snsId: 'SNS234567',
  },
  // Dr. Johnson's patients
  {
    id: '3',
    doctorId: '2',
    doctor: mockDoctors[1],
    name: 'Michael Brown',
    email: 'michael@example.com',
    phone: '+1 (555) 765-4321',
    address: '321 Maple Drive, Springfield, IL 62706',
    photo: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=400&fit=crop',
    snsId: 'SNS345678',
  },
  {
    id: '4',
    doctorId: '2',
    doctor: mockDoctors[1],
    name: 'Sarah Davis',
    email: 'sarah@example.com',
    phone: '+1 (555) 876-5432',
    address: '654 Pine Road, Springfield, IL 62707',
    photo: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&h=400&fit=crop',
    snsId: 'SNS567890',
  },
  {
    id: '6',
    doctorId: '2',
    doctor: mockDoctors[1],
    name: 'Emily Martinez',
    email: 'emily.m@example.com',
    phone: '+1 (555) 432-1098',
    address: '987 Birch Street, Springfield, IL 62709',
    photo: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&h=400&fit=crop',
    snsId: 'SNS678901',
  },
  // Dr. Williams' patients
  {
    id: '7',
    doctorId: '3',
    doctor: mockDoctors[2],
    name: 'David Wilson',
    email: 'david.w@example.com',
    phone: '+1 (555) 321-0987',
    address: '147 Spruce Avenue, Springfield, IL 62710',
    photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop',
    snsId: 'SNS789123',
  },
  {
    id: '8',
    doctorId: '3',
    doctor: mockDoctors[2],
    name: 'Jennifer Lopez',
    email: 'jennifer.l@example.com',
    phone: '+1 (555) 210-9876',
    address: '258 Willow Drive, Springfield, IL 62711',
    photo: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&h=400&fit=crop',
    snsId: 'SNS890234',
  },
  {
    id: '9',
    doctorId: '3',
    doctor: mockDoctors[2],
    name: 'James Taylor',
    email: 'james.t@example.com',
    phone: '+1 (555) 109-8765',
    address: '369 Ash Circle, Springfield, IL 62712',
    photo: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=400&fit=crop',
    snsId: 'SNS901345',
  },
]

export const mockExercises: Exercise[] = [
  {
    id: '1',
    doctorId: '0',
    name: 'Push-ups',
    description: 'A classic upper body exercise that strengthens chest, shoulders, and triceps.',
    jsonData: { difficulty: 'medium' },
  },
  {
    id: '2',
    doctorId: '0',
    name: 'Squats',
    description: 'A fundamental lower body exercise targeting quadriceps, hamstrings, and glutes.',
    jsonData: { difficulty: 'medium' },
  },
  {
    id: '3',
    doctorId: '0',
    name: 'Planks',
    description: 'Core strengthening exercise that improves stability and endurance.',
    jsonData: { difficulty: 'hard' },
  },
]

export const mockPlans: Plan[] = [
  // Dr. Smith's plans (Orthopedic)
  {
    id: '1',
    doctorId: '1',
    doctor: mockDoctor,
    patientId: '1',
    patient: mockPatients[0],
    title: 'Upper Body Strength Training',
    description: 'A comprehensive upper body workout plan focusing on chest, shoulders, and arms.',
    difficulty: 'intermediate',
    exercises: [
      { exerciseId: '1', sets: 3, repetitions: 10, duration: 5, exercise: mockExercises[0] },
      { exerciseId: '2', sets: 3, repetitions: 15, duration: 7, exercise: mockExercises[1] },
    ],
    score: 8.5,
    rating: 4,
    videoUrl: 'https://example.com/videos/upper-body.mp4',
    imageUrl: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=400&h=300&fit=crop',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: '2',
    doctorId: '1',
    doctor: mockDoctor,
    patientId: '2',
    patient: mockPatients[1],
    title: 'Core Stability Program',
    description: 'An advanced core training regimen designed to build strength and stability.',
    difficulty: 'advanced',
    exercises: [
      { exerciseId: '2', sets: 4, repetitions: 20, duration: 10, exercise: mockExercises[1] },
      { exerciseId: '3', sets: 3, repetitions: 30, duration: 12, exercise: mockExercises[2] },
    ],
    score: 9,
    rating: 5,
    videoUrl: 'https://example.com/videos/core-stability.mp4',
    imageUrl: 'https://images.unsplash.com/photo-1599058917212-d750089bc07e?w=400&h=300&fit=crop',
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-01-10'),
  },
  {
    id: '5',
    doctorId: '1',
    doctor: mockDoctor,
    patientId: '5',
    patient: mockPatients[2],
    title: 'Post-Injury Rehabilitation',
    description:
      'Gentle rehabilitation program for post-surgical recovery focusing on gradual strength building.',
    difficulty: 'beginner',
    exercises: [
      { exerciseId: '3', sets: 2, repetitions: 15, duration: 10, exercise: mockExercises[2] },
      { exerciseId: '1', sets: 2, repetitions: 8, duration: 6, exercise: mockExercises[0] },
    ],
    score: 7.5,
    rating: 4,
    videoUrl: 'https://example.com/videos/rehab.mp4',
    imageUrl: 'https://images.unsplash.com/photo-1578496323521-2f73b2ce2c09?w=400&h=300&fit=crop',
    createdAt: new Date('2024-01-18'),
    updatedAt: new Date('2024-01-18'),
  },
  // Dr. Johnson's plans (Physical Therapy)
  {
    id: '3',
    doctorId: '2',
    doctor: mockDoctors[1],
    patientId: '3',
    patient: mockPatients[3],
    title: 'Lower Body Strengthening',
    description:
      'A focused lower body workout program targeting quadriceps, hamstrings, and glutes.',
    difficulty: 'intermediate',
    exercises: [
      { exerciseId: '2', sets: 3, repetitions: 15, duration: 8, exercise: mockExercises[1] },
      { exerciseId: '3', sets: 4, repetitions: 20, duration: 10, exercise: mockExercises[2] },
    ],
    score: 8,
    rating: 4,
    videoUrl: 'https://example.com/videos/lower-body.mp4',
    imageUrl: 'https://images.unsplash.com/photo-1533902633539-824ce1c56804?w=400&h=300&fit=crop',
    createdAt: new Date('2024-01-12'),
    updatedAt: new Date('2024-01-12'),
  },
  {
    id: '4',
    doctorId: '2',
    doctor: mockDoctors[1],
    patientId: '4',
    patient: mockPatients[4],
    title: 'Full Body Circuit Training',
    description: 'A comprehensive full-body workout combining cardio and strength exercises.',
    difficulty: 'advanced',
    exercises: [
      { exerciseId: '1', sets: 3, repetitions: 12, duration: 6, exercise: mockExercises[0] },
      { exerciseId: '2', sets: 3, repetitions: 18, duration: 9, exercise: mockExercises[1] },
    ],
    score: 8.5,
    rating: 5,
    videoUrl: 'https://example.com/videos/full-body.mp4',
    imageUrl: 'https://images.unsplash.com/photo-1541534867517-c89cba53ae8f?w=400&h=300&fit=crop',
    createdAt: new Date('2024-01-08'),
    updatedAt: new Date('2024-01-08'),
  },
  {
    id: '6',
    doctorId: '2',
    doctor: mockDoctors[1],
    patientId: '6',
    patient: mockPatients[5],
    title: 'Flexibility & Mobility Training',
    description:
      'Comprehensive stretching and mobility program designed to improve range of motion.',
    difficulty: 'intermediate',
    exercises: [
      { exerciseId: '1', sets: 3, repetitions: 20, duration: 8, exercise: mockExercises[0] },
      { exerciseId: '3', sets: 4, repetitions: 25, duration: 10, exercise: mockExercises[2] },
    ],
    score: 8.2,
    rating: 4,
    videoUrl: 'https://example.com/videos/flexibility.mp4',
    imageUrl: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=400&h=300&fit=crop',
    createdAt: new Date('2024-01-14'),
    updatedAt: new Date('2024-01-14'),
  },
  // Dr. Williams' plans (Sports Medicine)
  {
    id: '7',
    doctorId: '3',
    doctor: mockDoctors[2],
    patientId: '7',
    patient: mockPatients[6],
    title: 'Athletic Performance Enhancement',
    description:
      'High-intensity training program designed to improve athletic performance and endurance.',
    difficulty: 'advanced',
    exercises: [
      { exerciseId: '2', sets: 4, repetitions: 25, duration: 12, exercise: mockExercises[1] },
      { exerciseId: '3', sets: 3, repetitions: 30, duration: 10, exercise: mockExercises[2] },
    ],
    score: 9,
    rating: 5,
    videoUrl: 'https://example.com/videos/athletic.mp4',
    imageUrl: 'https://images.unsplash.com/photo-1517836357463-d25ddfcbf042?w=400&h=300&fit=crop',
    createdAt: new Date('2024-01-16'),
    updatedAt: new Date('2024-01-16'),
  },
  {
    id: '8',
    doctorId: '3',
    doctor: mockDoctors[2],
    patientId: '8',
    patient: mockPatients[7],
    title: 'Injury Prevention Program',
    description:
      'Specialized program focusing on injury prevention through balanced strength and flexibility training.',
    difficulty: 'intermediate',
    exercises: [
      { exerciseId: '1', sets: 3, repetitions: 15, duration: 7, exercise: mockExercises[0] },
      { exerciseId: '3', sets: 3, repetitions: 20, duration: 8, exercise: mockExercises[2] },
    ],
    score: 8.3,
    rating: 4,
    videoUrl: 'https://example.com/videos/prevention.mp4',
    imageUrl: 'https://images.unsplash.com/photo-1475274047050-1d0c0975c63e?w=400&h=300&fit=crop',
    createdAt: new Date('2024-01-17'),
    updatedAt: new Date('2024-01-17'),
  },
  {
    id: '9',
    doctorId: '3',
    doctor: mockDoctors[2],
    patientId: '9',
    patient: mockPatients[8],
    title: 'Cardio & Conditioning Bootcamp',
    description:
      'Intense cardiovascular and conditioning program for competitive athletes and active individuals.',
    difficulty: 'advanced',
    exercises: [
      { exerciseId: '2', sets: 5, repetitions: 30, duration: 15, exercise: mockExercises[1] },
      { exerciseId: '1', sets: 4, repetitions: 15, duration: 10, exercise: mockExercises[0] },
    ],
    score: 8.7,
    rating: 5,
    videoUrl: 'https://example.com/videos/cardio-bootcamp.mp4',
    imageUrl: 'https://images.unsplash.com/photo-1549576528-cabeb36b37c9?w=400&h=300&fit=crop',
    createdAt: new Date('2024-01-13'),
    updatedAt: new Date('2024-01-13'),
  },
]
